@extends('backend.layouts.master')
@section('title','Attendance Dashboard')
@section('content')
@include('backend.attendance._styles')
<div class="main-content atl-shell"><div class="page-content"><div class="container-fluid">
<div class="atl-hero p-4 mb-4 d-flex flex-wrap justify-content-between align-items-center gap-3"><div><h3 class="text-white mb-1">Attendance & Leave</h3><div class="text-white-50">{{ now()->format('l, d F Y') }}</div></div><div class="d-flex gap-2 flex-wrap"><a class="btn btn-light" href="{{route('admin.attendance.index')}}">Mark Attendance</a><a class="btn btn-outline-light" href="{{route('admin.attendance.monthly')}}">Monthly View</a><a class="btn btn-outline-light" href="{{route('admin.attendance.report')}}">Reports</a></div></div>
@php($stats=['Eligible Users'=>[$eligible,'primary'],'Present'=>[(int)($counts['present']??0),'success'],'Absent'=>[(int)($counts['absent']??0),'danger'],'On Leave'=>[(int)($counts['on_leave']??0),'info'],'Half Day'=>[(int)($counts['half_day']??0),'warning'],'Unmarked'=>[$unmarked,'secondary']])
<div class="row g-3 mb-4">@foreach($stats as $label=>$item)<div class="col-6 col-md-4 col-xl-2"><div class="card atl-stat h-100"><div class="card-body"><div class="text-muted small">{{$label}}</div><div class="fs-2 fw-bold text-{{$item[1]}}">{{$item[0]}}</div></div></div></div>@endforeach</div>
<div class="row g-4"><div class="col-lg-7"><div class="card atl-card"><div class="card-header"><h5 class="mb-0">Recent Attendance Activity</h5></div><div class="card-body table-responsive"><table class="table attendance-table"><thead><tr><th>User</th><th>Date</th><th>Status</th><th>Updated</th></tr></thead><tbody>@forelse($recentAttendance as $row)<tr><td>{{$row->user->name}}</td><td>{{$row->attendance_date->format('d M Y')}}</td><td><span class="status-badge s-{{$row->status}}">{{ucwords(str_replace('_',' ',$row->status))}}</span></td><td>{{$row->updated_at->diffForHumans()}}</td></tr>@empty<tr><td colspan="4" class="text-center text-muted">No attendance activity.</td></tr>@endforelse</tbody></table></div></div></div>
<div class="col-lg-5"><div class="card atl-card mb-4"><div class="card-header"><h5 class="mb-0">This Month</h5></div><div class="card-body">@foreach(\App\Models\Attendance::STATUSES as $status)<div class="d-flex justify-content-between border-bottom py-2"><span>{{ucwords(str_replace('_',' ',$status))}}</span><strong>{{(int)($monthCounts[$status]??0)}}</strong></div>@endforeach</div></div><div class="card atl-card"><div class="card-header"><h5 class="mb-0">Recent Leave Activity</h5></div><div class="list-group list-group-flush">@forelse($recentLeaves as $leave)<div class="list-group-item"><div class="d-flex justify-content-between"><strong>{{$leave->user->name}}</strong><span class="badge bg-{{$leave->status==='approved'?'success':($leave->status==='rejected'?'danger':'warning')}}">{{ucfirst($leave->status)}}</span></div><small class="text-muted">{{$leave->leave_type}} · {{$leave->from_date->format('d M')}} – {{$leave->to_date->format('d M')}}</small></div>@empty<div class="p-3 text-muted">No leave activity.</div>@endforelse</div></div></div></div>
</div></div></div>
@endsection
