@extends('backend.layouts.master')
@section('title','Attendance Reports')
@section('content')
@include('backend.attendance._styles')
<div class="main-content atl-shell"><div class="page-content"><div class="container-fluid"><div class="d-flex justify-content-between mb-3"><h3>Attendance Reports</h3><a class="btn btn-outline-dark" href="{{route('admin.attendance.dashboard')}}">Dashboard</a></div><div class="card atl-card mb-3"><div class="card-body"><form id="report-filter" class="row g-2"><div class="col-md-2"><input type="date" name="from_date" value="{{$filters['from_date']??''}}" class="form-control" title="From date"></div><div class="col-md-2"><input type="date" name="to_date" value="{{$filters['to_date']??''}}" class="form-control" title="To date"></div><div class="col-md-2"><select name="month" class="form-select"><option value="">Any month</option>@for($m=1;$m<=12;$m++)<option value="{{$m}}" @selected(($filters['month']??'')==$m)>{{date('F',mktime(0,0,0,$m,1))}}</option>@endfor</select></div><div class="col-md-1"><input name="year" type="number" value="{{$filters['year']??''}}" min="2000" max="2100" placeholder="Year" class="form-control"></div><div class="col-md-2"><select name="user_id" class="form-select"><option value="">All users</option>@foreach($users as $u)<option value="{{$u->id}}" @selected(($filters['user_id']??'')==$u->id)>{{$u->name}}</option>@endforeach</select></div><div class="col-md-2"><select name="status" class="form-select"><option value="">All statuses</option>@foreach(\App\Models\Attendance::STATUSES as $s)<option value="{{$s}}" @selected(($filters['status']??'')===$s)>{{ucwords(str_replace('_',' ',$s))}}</option>@endforeach</select></div><div class="col-md-1"><button class="btn btn-dark w-100">Go</button></div></form></div></div>
@can('export',\App\Models\Attendance::class)<div class="d-flex flex-wrap gap-2 mb-3">@foreach(['print'=>'Print','pdf'=>'PDF','xlsx'=>'Excel','csv'=>'CSV'] as $format=>$label)<a target="{{$format==='print'?'_blank':'_self'}}" class="btn btn-outline-secondary btn-sm export-link" href="{{route('admin.attendance.export',$format)}}">{{$label}}</a>@endforeach</div>@endcan
<div class="row g-2 mb-3">@foreach(\App\Models\Attendance::STATUSES as $s)<div class="col-6 col-md-4 col-xl-2"><div class="card atl-stat"><div class="card-body py-3"><small class="text-muted">{{ucwords(str_replace('_',' ',$s))}}</small><div class="fs-4 fw-bold">{{(int)($summary[$s]??0)}}</div></div></div></div>@endforeach</div>
<div class="card atl-card"><div class="table-responsive"><table class="table attendance-table mb-0"><thead><tr><th>Date</th><th>User</th><th>Status</th><th>Check In</th><th>Check Out</th><th>Working Hours</th><th>Leave</th><th>Remarks</th></tr></thead><tbody>@forelse($records as $a)<tr><td>{{$a->attendance_date->format('d M Y')}}</td><td>{{$a->user->name}}</td><td><span class="status-badge s-{{$a->status}}">{{ucwords(str_replace('_',' ',$a->status))}}</span></td><td>{{$a->check_in?:'—'}}</td><td>{{$a->check_out?:'—'}}</td><td>{{sprintf('%d:%02d',intdiv($a->working_minutes,60),$a->working_minutes%60)}}</td><td>{{$a->leaveRequest?->leave_type?:'—'}}</td><td>{{$a->remarks?:'—'}}</td></tr>@empty<tr><td colspan="8" class="text-center p-4">No records match these filters.</td></tr>@endforelse</tbody></table></div><div class="card-footer">{{$records->links()}}</div></div></div></div></div>
@endsection
@section('script')<script>document.querySelectorAll('.export-link').forEach(a=>a.addEventListener('click',function(){this.href=this.href.split('?')[0]+'?'+new URLSearchParams(new FormData(document.getElementById('report-filter'))).toString()}));</script>@endsection
